import new_text_prediction_post_0909
print(new_text_prediction_post_0909.error_df['Reconstruction_error'].values)



